language: node_js
node_js:
  - "4"
  - "6"

sudo: false

matrix:
  fast_finish: true

cache:
  directories:
    - bower_components
    - node_modules

before_install:
  - npm install -g gulp bower

before_script:
  - npm install
  - bower install

script:
  - gulp stage

after_success:
  - gulp build

notifications:
    email:
        on_failure: always
